language: go

go:
  - 1.12.x

git:
  depth: 1

notifications:
  email: false

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make
  - make test
  - golangci-lint run
